
#This script is used to generate synthetic data for the chess dataset, using the gpt_prompt column of the filtered_dataset_small_with_prompts_final dataset.
#The synthetic data is generated by using the gpt_prompt column, prompting a model with the given prompt to generate a reasoning trace.
#then, we can use the model's reasoning trace to generate synthetic data, to train a model to output the best move for a given board layout with the reasoning trace.

from datasets import Dataset
import openai

open
ds = Dataset.load_from_disk("filtered_dataset_small_with_prompts_final")

def generate_synthetic_data(prompt):





