
#This script is used to generate synthetic data for the chess dataset, using the gpt_prompt column of the filtered_dataset_small_with_prompts_final dataset.
#The synthetic data is generated by using the gpt_prompt column, prompting a model with the given prompt to generate a reasoning trace.
#then, we can use the model's reasoning trace to generate synthetic data, to train a model to output the best move for a given board layout with the reasoning trace.
from datasets import Dataset
import re
from openai import OpenAI

ds = Dataset.load_from_disk("filtered_dataset_small_with_prompts_final")
ds = ds.shuffle(seed=42)
ds = ds.select(range(0,len(ds),10))
api_key = "meow"
with open("api_key.txt", "r") as f:
    api_key = f.readline().strip()
client = OpenAI(api_key=api_key)

def generate_synthetic_data(prompt):
    response = client.chat.completions.create(
        model="gpt-4o",
        messages=[{"role": "system", "content": prompt}],
        max_tokens=2000
    )
    return response.choices[0].message.content

def check_gpt4_output(generated, best_move):
    if "<answer>" not in generated or "<think>" not in generated or "</answer>" not in generated or "</think>" not in generated:
        return False
    if format_reward_func(generated) == 0.0:
        return False
    move = generated.split("<answer>")[1].split("</answer>")[0].strip()
    if move in best_move:
        return True
    return False
def format_reward_func(completion):
    completion = completion.replace("\n", "")
    if completion[0:7] == "<think>": 
        pattern = r"^<think>.*?</think><answer>.*?</answer>$"
        return 2.0 if re.match(pattern, completion) else 0.0
    return 0.0
ds = ds.map(lambda x: {'generated': generate_synthetic_data(x["prompt"])}, num_proc=54)

ds = ds.map(lambda x: {'is_correct': check_gpt4_output(x["generated"], x["best_move"])}, num_proc=54)
ds = ds.filter(lambda x: x["is_correct"] == True)
ds.save_to_disk("sft_data")






